### ISSUE TITLE
Bundling core

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/open-scd-core#20]
I'm trying to bundle core as part of rollup to allow it to be accessed from gh-pages without fetching it from the gh-pages branch because this seems brittle and easily broken.

After updating some TypeScript dependencies the main issue seemed to be the core's importing of locales:

```bash
[08:15:32] mulhollandd  $        ~/Documents/open-scd/bits/danyill/oscd-rename-ieds   main  npm run bundle
> oscd-rename-ieds@0.0.0 bundle
> rimraf dist && rollup -c rollup.config.js
./oscd-rename-ieds.ts, ./openscd.ts → dist...
[!] (plugin rollup-plugin-import-meta-assets) Error: invalid import "new URL(`locales/${locale}.js`, import.meta.url)". Variable bare imports are not supported, imports must start with ./ in the static part of t
he import. For example: import(`./foo/${bar}.js`).
node_modules/@openenergytools/open-scd-core/open-scd.ts
Error: invalid import "new URL(`locales/${locale}.js`, import.meta.url)". Variable bare imports are not supported, imports must start with ./ in the static part of the import. For example: import(`./foo/${bar}.j
s`).
   at dynamicImportToGlob (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/@rollup/plugin-dynamic-import-vars/dist/cjs/index.js:111:11)
   at Object.enter (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/@web/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js:98:26)
   at AsyncWalker.visit (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/estree-walker/dist/umd/estree-walker.js:234:23)
   at AsyncWalker.visit (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/estree-walker/dist/umd/estree-walker.js:271:18)
   at processTicksAndRejections (node:internal/process/task_queues:95:5)
   at AsyncWalker.visit (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/estree-walker/dist/umd/estree-walker.js:271:7)
   at AsyncWalker.visit (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/estree-walker/dist/umd/estree-walker.js:271:7)
   at AsyncWalker.visit (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/estree-walker/dist/umd/estree-walker.js:271:7)
   at AsyncWalker.visit (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/estree-walker/dist/umd/estree-walker.js:264:15)
   at AsyncWalker.visit (/home/mulhollandd/Documents/open-scd/bits/danyill/oscd-rename-ieds/node_modules/estree-walker/dist/umd/estree-walker.js:264:15)
```

The following small change allowed it to be bundled correctly and it appears to work:

```diff
const { getLocale, setLocale } = configureLocalization({
  sourceLocale,
  targetLocales,
  loadLocale: locale =>
-    import(new URL(`locales/${locale}.js`, import.meta.url).href),
+    import(new URL(`./locales/${locale}.js`, import.meta.url).href),
});
```

**Comment by danyill** [comment]
I would do a PR but I notice we are also doing something specific in open-scd's `rollup.config.js` for locales so perhaps it is not that simple or this might break that. 

https://github.com/OpenEnergyTools/open-scd-core/blob/8086a84a640a83331fdadd2f4f91941686af7f8f/rollup.config.js#L7-L21

**Comment by danyill** [comment]
I will do a PR with a single `.` in it as @ca-d does not think the rollup configuration requires changes.
